# Generated by Django 5.0.1 on 2024-02-02 18:03

import django.core.validators
import peststagram.photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('picture', models.ImageField(upload_to='photos/', validators=[peststagram.photos.validators.validate_photo_size])),
                ('description', models.TextField(blank=True, max_length=300, null=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('date_of_publication', models.DateField(auto_now_add=True)),
                ('time_of_modification', models.DateTimeField(auto_now=True)),
                ('tagged_pests', models.ManyToManyField(blank=True, related_name='tagged_pests', to='pests.pest')),
            ],
        ),
    ]
