# Generated by Django 5.0.1 on 2024-02-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('photo', models.URLField()),
                ('description', models.TextField()),
                ('date_of_sight', models.DateField()),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
        ),
    ]
